# Generated by Django 5.2.7 on 2025-10-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Template name", max_length=100, unique=True)),
                ("description", models.TextField(blank=True, help_text="Description of this template")),
                ("image", models.ImageField(help_text="QSL card template image", upload_to="card_templates/")),
                (
                    "is_active",
                    models.BooleanField(default=False, help_text="Whether this template is currently active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Card Template",
                "verbose_name_plural": "Card Templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
