# Generated by Django 5.2.7 on 2025-10-15 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eqsl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QSO",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("my_call", models.CharField(help_text="Your callsign", max_length=20)),
                ("my_gridsquare", models.CharField(blank=True, help_text="Your grid square", max_length=10)),
                ("my_rig", models.CharField(blank=True, help_text="Your radio equipment", max_length=100)),
                ("call", models.CharField(db_index=True, help_text="Contact's callsign", max_length=20)),
                ("name", models.CharField(blank=True, help_text="Contact's name", max_length=100)),
                ("email", models.EmailField(blank=True, help_text="Contact's email address", max_length=254)),
                ("frequency", models.FloatField(help_text="Frequency in MHz")),
                ("band", models.CharField(help_text="Band (e.g., 20m, 2m)", max_length=10)),
                ("mode", models.CharField(help_text="Mode (e.g., SSB, CW, FT8)", max_length=20)),
                ("rst_sent", models.CharField(help_text="RST sent", max_length=10)),
                ("rst_rcvd", models.CharField(help_text="RST received", max_length=10)),
                ("tx_pwr", models.IntegerField(help_text="Transmit power in watts")),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, help_text="QSO date and time"
                    ),
                ),
                ("sota_ref", models.CharField(blank=True, help_text="SOTA reference", max_length=20)),
                ("pota_ref", models.CharField(blank=True, help_text="POTA reference", max_length=20)),
                ("country", models.CharField(blank=True, help_text="Contact's country", max_length=100)),
                ("lang", models.CharField(blank=True, default="en", help_text="Language code", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QSO",
                "verbose_name_plural": "QSOs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="eqsl_qso_timesta_24e1b3_idx"),
                    models.Index(fields=["call"], name="eqsl_qso_call_a265b4_idx"),
                ],
            },
        ),
    ]
