# Generated by Django 5.2.7 on 2025-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eqsl", "0003_emailqsl"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardtemplate",
            name="html_template",
            field=models.TextField(blank=True, help_text="Jinja2 template for email body"),
        ),
        migrations.AddField(
            model_name="cardtemplate",
            name="language",
            field=models.CharField(
                blank=True, default="en", help_text="Language code for this template", max_length=10
            ),
        ),
    ]
