# Generated by Django 5.2.7 on 2025-10-21 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqsl', '0006_alter_cardtemplate_python_render_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'default', 'simple')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this render template')),
                ('python_render_code', models.TextField(help_text='Python code defining a render(card_template, qso) function that returns a PIL Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Render Template',
                'verbose_name_plural': 'Render Templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cardtemplate',
            name='python_render_code',
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='render_template',
            field=models.ForeignKey(blank=True, help_text='Render template used to generate QSL card images', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_templates', to='eqsl.rendertemplate'),
        ),
    ]
