# Generated by Django 5.2.7 on 2026-07-24 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eqsl", "0008_populate_render_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailqsl",
            name="error_message",
            field=models.TextField(blank=True, help_text="Error details if sending failed"),
        ),
        migrations.AlterField(
            model_name="emailqsl",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("bounced", "Bounced"),
                ],
                default="sent",
                help_text="Email delivery status",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Template name", max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("es", "Spanish"), ("fr", "French")],
                        default="en",
                        help_text="Template language",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(help_text="Email subject (Django template syntax)", max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Email HTML body (Django template syntax, {{ cid }} for the inline card image)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this template can be used")),
                ("is_default", models.BooleanField(default=False, help_text="Default template for this language")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["language", "name"],
                "unique_together": {("language", "name")},
            },
        ),
        migrations.AddField(
            model_name="emailqsl",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Email template used",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_qsls",
                to="eqsl.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="SendingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_name",
                    models.CharField(default="Your Friendly Ham", help_text="Sender display name", max_length=100),
                ),
                (
                    "reply_to_email",
                    models.EmailField(blank=True, help_text="Reply-To address (optional)", max_length=254),
                ),
                ("batch_size", models.PositiveIntegerField(default=10, help_text="Maximum emails per batch")),
                (
                    "delay_between_emails_s",
                    models.PositiveIntegerField(default=5, help_text="Delay between emails in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_card_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Card template used when none is specified",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="eqsl.cardtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sending Settings",
                "verbose_name_plural": "Sending Settings",
            },
        ),
    ]
