# Generated by Django 5.2.7 on 2026-07-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eqsl", "0010_populate_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="qso",
            name="qrz_lookup_at",
            field=models.DateTimeField(
                blank=True, help_text="When contact info was last looked up on QRZ.com", null=True
            ),
        ),
    ]
