# Generated by Django 5.2.7 on 2026-07-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eqsl", "0011_qso_qrz_lookup_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendingsettings",
            name="qrz_api_key",
            field=models.CharField(blank=True, help_text="QRZ Logbook API key (blank = use .env)", max_length=100),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="qrz_password",
            field=models.CharField(blank=True, help_text="QRZ.com password (blank = use .env)", max_length=255),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="qrz_username",
            field=models.CharField(blank=True, help_text="QRZ.com username (blank = use .env)", max_length=100),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="smtp_from_email",
            field=models.EmailField(blank=True, help_text="Sender email address (blank = use .env)", max_length=254),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="smtp_host",
            field=models.CharField(blank=True, help_text="SMTP server (blank = use .env)", max_length=255),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="smtp_password",
            field=models.CharField(blank=True, help_text="SMTP password (blank = use .env)", max_length=255),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="smtp_port",
            field=models.PositiveIntegerField(blank=True, help_text="SMTP port (blank = use .env)", null=True),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True, help_text="Use STARTTLS"),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="smtp_username",
            field=models.CharField(blank=True, help_text="SMTP username (blank = use .env)", max_length=255),
        ),
    ]
