# Generated by Django 5.2.7 on 2026-07-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eqsl", "0012_sendingsettings_qrz_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sendingsettings",
            name="lotw_last_sync",
            field=models.DateTimeField(blank=True, help_text="Last successful LoTW sync", null=True),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="lotw_password",
            field=models.CharField(blank=True, help_text="LoTW password (blank = use .env)", max_length=255),
        ),
        migrations.AddField(
            model_name="sendingsettings",
            name="lotw_username",
            field=models.CharField(blank=True, help_text="LoTW username (blank = use .env)", max_length=100),
        ),
    ]
